services:

  diversolab_app_web:
    build:
      context: /workspace
      dockerfile: /workspace/diversolab_app/docker/Dockerfile.diversolab_app.dev
    container_name: diversolab_app_web
    volumes:
      - ${SPLENT_HOST_PROJECT_DIR}:/workspace
    env_file:
      - /workspace/diversolab_app/docker/.env
    ports:
      - "5125:5000"
    depends_on:
      diversolab_app_db:
        condition: service_healthy
    environment:
      - MAIL_HOST=diversolab_app_mailhog
      - MAIL_PORT=1025
    networks:
      - splent_network
    command: [ "tail", "-f", "/dev/null" ]

  diversolab_app_db:
    image: mariadb:11.4
    container_name: diversolab_app_db
    env_file:
      - /workspace/diversolab_app/docker/.env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33185:3306"
    volumes:
      - diversolab_app_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u$${MARIADB_USER} -p$${MARIADB_PASSWORD} -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    networks:
      - splent_network

  diversolab_app_mailhog:
    image: mailhog/mailhog:latest
    container_name: diversolab_app_mailhog
    ports:
      - "8025:8025"
    networks:
      - splent_network

volumes:
  diversolab_app_db_data:

networks:
  splent_network:
    external: true
